version: '2'

services:
  dmall-order-service:
    image: '${DMALL_DOCKER_REGISTRY}/${GROUP_PATH}/order-service:${BUILD_NUMBER}'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8084:8084"
    external_links:
      - dmall-config-server/dmall-config-server:dmall-config-server
      - dmall-registry-server/dmall-registry-server:dmall-registry-server
    